'use strict';

exports.categories = [
  {
    "category_id":34,
    "parent_category_id":26,
    "category_level":3,
    "title":"Primary and Secondary Schools",
    "naic_code":611110,
    "sic_code":"8210"
  },
  {
    "category_id":1,
    "parent_category_id":null,
    "category_level":1,
    "title":"Factual Places",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":2,
    "parent_category_id":1,
    "category_level":1,
    "title":"Automotive",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":72,
    "parent_category_id":62,
    "category_level":2,
    "title":"Holistic, Alternative and Naturopathic Medicine",
    "naic_code":6213,
    "sic_code":"8040"
  },
  {
    "category_id":155,
    "parent_category_id":149,
    "category_level":3,
    "title":"Health and Diet Food",
    "naic_code":446191,
    "sic_code":"2099"
  },
  {
    "category_id":161,
    "parent_category_id":123,
    "category_level":2,
    "title":"Luggage",
    "naic_code":44832,
    "sic_code":"5948"
  },
  {
    "category_id":160,
    "parent_category_id":123,
    "category_level":2,
    "title":"Hobby and Collectibles",
    "naic_code":45112,
    "sic_code":"5945"
  },
  {
    "category_id":9,
    "parent_category_id":2,
    "category_level":2,
    "title":"Maintenance and Repair",
    "naic_code":811111,
    "sic_code":"7500"
  },
  {
    "category_id":378,
    "parent_category_id":372,
    "category_level":2,
    "title":"Cycling",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":137,
    "parent_category_id":123,
    "category_level":2,
    "title":"Construction Supplies",
    "naic_code":4441,
    "sic_code":"5200"
  },
  {
    "category_id":52,
    "parent_category_id":20,
    "category_level":2,
    "title":"Public and Social Services",
    "naic_code":624,
    "sic_code":"8300"
  },
  {
    "category_id":110,
    "parent_category_id":107,
    "category_level":2,
    "title":"Historic and Protected Sites",
    "naic_code":712120,
    "sic_code":null
  },
  {
    "category_id":225,
    "parent_category_id":219,
    "category_level":3,
    "title":"Financial Planning and Investments",
    "naic_code":523,
    "sic_code":"6700"
  },
  {
    "category_id":273,
    "parent_category_id":177,
    "category_level":2,
    "title":"Machine Shops",
    "naic_code":332710,
    "sic_code":null
  },
  {
    "category_id":95,
    "parent_category_id":83,
    "category_level":3,
    "title":"Ophthalmologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":132,
    "parent_category_id":123,
    "category_level":2,
    "title":"Children",
    "naic_code":448130,
    "sic_code":"5640"
  },
  {
    "category_id":236,
    "parent_category_id":235,
    "category_level":3,
    "title":"Architects",
    "naic_code":541310,
    "sic_code":"8910"
  },
  {
    "category_id":20,
    "parent_category_id":1,
    "category_level":1,
    "title":"Community and Government",
    "naic_code":92,
    "sic_code":null
  },
  {
    "category_id":237,
    "parent_category_id":235,
    "category_level":3,
    "title":"Carpenters",
    "naic_code":23835,
    "sic_code":"1751"
  },
  {
    "category_id":238,
    "parent_category_id":235,
    "category_level":3,
    "title":"Carpet and Flooring",
    "naic_code":238330,
    "sic_code":"1750"
  },
  {
    "category_id":26,
    "parent_category_id":20,
    "category_level":2,
    "title":"Education",
    "naic_code":61,
    "sic_code":"8200"
  },
  {
    "category_id":239,
    "parent_category_id":235,
    "category_level":3,
    "title":"Contractors",
    "naic_code":2389,
    "sic_code":"1700"
  },
  {
    "category_id":241,
    "parent_category_id":239,
    "category_level":4,
    "title":"Deck and Patio",
    "naic_code":2389,
    "sic_code":"1700"
  },
  {
    "category_id":242,
    "parent_category_id":239,
    "category_level":4,
    "title":"Sewer",
    "naic_code":23711,
    "sic_code":"1700"
  },
  {
    "category_id":243,
    "parent_category_id":235,
    "category_level":3,
    "title":"Doors and Windows",
    "naic_code":2389,
    "sic_code":"1700"
  },
  {
    "category_id":247,
    "parent_category_id":235,
    "category_level":3,
    "title":"Heating, Ventilating and Air Conditioning",
    "naic_code":23822,
    "sic_code":"1710"
  },
  {
    "category_id":240,
    "parent_category_id":239,
    "category_level":4,
    "title":"Bathrooms",
    "naic_code":2389,
    "sic_code":"1700"
  },
  {
    "category_id":251,
    "parent_category_id":235,
    "category_level":3,
    "title":"Interior Design",
    "naic_code":541410,
    "sic_code":"1720"
  },
  {
    "category_id":252,
    "parent_category_id":235,
    "category_level":3,
    "title":"Kitchens",
    "naic_code":23822,
    "sic_code":"1700"
  },
  {
    "category_id":265,
    "parent_category_id":235,
    "category_level":3,
    "title":"Upholstery",
    "naic_code":337121,
    "sic_code":"5714"
  },
  {
    "category_id":260,
    "parent_category_id":235,
    "category_level":3,
    "title":"Pools and Spas",
    "naic_code":238990,
    "sic_code":"7349"
  },
  {
    "category_id":38,
    "parent_category_id":20,
    "category_level":2,
    "title":"Government Lobbyists",
    "naic_code":92119,
    "sic_code":null
  },
  {
    "category_id":261,
    "parent_category_id":235,
    "category_level":3,
    "title":"Roofers",
    "naic_code":23816,
    "sic_code":"1760"
  },
  {
    "category_id":40,
    "parent_category_id":20,
    "category_level":2,
    "title":"Law Enforcement and Public Safety",
    "naic_code":922,
    "sic_code":null
  },
  {
    "category_id":133,
    "parent_category_id":123,
    "category_level":2,
    "title":"Computers and Electronics",
    "naic_code":443142,
    "sic_code":"5732"
  },
  {
    "category_id":438,
    "parent_category_id":432,
    "category_level":3,
    "title":"Resorts",
    "naic_code":72119,
    "sic_code":"7000"
  },
  {
    "category_id":437,
    "parent_category_id":432,
    "category_level":3,
    "title":"Lodges and Vacation Rentals",
    "naic_code":72119,
    "sic_code":"7000"
  },
  {
    "category_id":47,
    "parent_category_id":20,
    "category_level":2,
    "title":"Organizations and Associations",
    "naic_code":813410,
    "sic_code":"8600"
  },
  {
    "category_id":439,
    "parent_category_id":430,
    "category_level":2,
    "title":"Tourist Information and Services",
    "naic_code":5615,
    "sic_code":"4722"
  },
  {
    "category_id":62,
    "parent_category_id":1,
    "category_level":1,
    "title":"Healthcare",
    "naic_code":621,
    "sic_code":"8000"
  },
  {
    "category_id":440,
    "parent_category_id":430,
    "category_level":2,
    "title":"Travel Agents and Tour Operators",
    "naic_code":56152,
    "sic_code":"4722"
  },
  {
    "category_id":268,
    "parent_category_id":177,
    "category_level":2,
    "title":"Leather",
    "naic_code":316,
    "sic_code":"3100"
  },
  {
    "category_id":230,
    "parent_category_id":177,
    "category_level":2,
    "title":"Food and Beverage",
    "naic_code":722,
    "sic_code":"5410"
  },
  {
    "category_id":363,
    "parent_category_id":347,
    "category_level":4,
    "title":"Pizza",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":327,
    "parent_category_id":317,
    "category_level":3,
    "title":"Fairgrounds and Rodeos",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":70,
    "parent_category_id":62,
    "category_level":2,
    "title":"Emergency Services",
    "naic_code":624230,
    "sic_code":"8090"
  },
  {
    "category_id":404,
    "parent_category_id":372,
    "category_level":2,
    "title":"Soccer",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":114,
    "parent_category_id":112,
    "category_level":3,
    "title":"Mountains",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":408,
    "parent_category_id":372,
    "category_level":2,
    "title":"Water Sports",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":53,
    "parent_category_id":20,
    "category_level":2,
    "title":"Religious",
    "naic_code":8131,
    "sic_code":"8660"
  },
  {
    "category_id":28,
    "parent_category_id":26,
    "category_level":3,
    "title":"Art Lessons and Schools",
    "naic_code":611610,
    "sic_code":"8290"
  },
  {
    "category_id":107,
    "parent_category_id":1,
    "category_level":1,
    "title":"Landmarks",
    "naic_code":712,
    "sic_code":null
  },
  {
    "category_id":112,
    "parent_category_id":107,
    "category_level":2,
    "title":"Natural",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":83,
    "parent_category_id":62,
    "category_level":2,
    "title":"Physicians",
    "naic_code":62111,
    "sic_code":"8010"
  },
  {
    "category_id":118,
    "parent_category_id":107,
    "category_level":2,
    "title":"Parks",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":120,
    "parent_category_id":118,
    "category_level":3,
    "title":"Picnic Areas",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":123,
    "parent_category_id":1,
    "category_level":1,
    "title":"Retail",
    "naic_code":44,
    "sic_code":"52"
  },
  {
    "category_id":149,
    "parent_category_id":123,
    "category_level":2,
    "title":"Food and Beverage",
    "naic_code":445,
    "sic_code":"5800"
  },
  {
    "category_id":142,
    "parent_category_id":123,
    "category_level":2,
    "title":"Fashion",
    "naic_code":448,
    "sic_code":"5600"
  },
  {
    "category_id":138,
    "parent_category_id":123,
    "category_level":2,
    "title":"Convenience Stores",
    "naic_code":445120,
    "sic_code":"5540"
  },
  {
    "category_id":177,
    "parent_category_id":1,
    "category_level":1,
    "title":"Businesses and Services",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":193,
    "parent_category_id":177,
    "category_level":2,
    "title":"Advertising and Marketing",
    "naic_code":5418,
    "sic_code":"7310"
  },
  {
    "category_id":208,
    "parent_category_id":177,
    "category_level":2,
    "title":"Chemicals and Gasses",
    "naic_code":325,
    "sic_code":"5160"
  },
  {
    "category_id":210,
    "parent_category_id":177,
    "category_level":2,
    "title":"Corporate HQ",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":214,
    "parent_category_id":177,
    "category_level":2,
    "title":"Entertainment",
    "naic_code":71,
    "sic_code":"7929"
  },
  {
    "category_id":219,
    "parent_category_id":177,
    "category_level":2,
    "title":"Financial",
    "naic_code":52,
    "sic_code":"60"
  },
  {
    "category_id":232,
    "parent_category_id":230,
    "category_level":3,
    "title":"Distribution",
    "naic_code":4244,
    "sic_code":"2000"
  },
  {
    "category_id":166,
    "parent_category_id":123,
    "category_level":2,
    "title":"Pawn Shops",
    "naic_code":4533,
    "sic_code":"5930"
  },
  {
    "category_id":308,
    "parent_category_id":1,
    "category_level":1,
    "title":"Social",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":372,
    "parent_category_id":1,
    "category_level":1,
    "title":"Sports and Recreation",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":274,
    "parent_category_id":177,
    "category_level":2,
    "title":"Management",
    "naic_code":551,
    "sic_code":"7392"
  },
  {
    "category_id":275,
    "parent_category_id":177,
    "category_level":2,
    "title":"Manufacturing",
    "naic_code":31,
    "sic_code":"20"
  },
  {
    "category_id":277,
    "parent_category_id":177,
    "category_level":2,
    "title":"Personal Care",
    "naic_code":8121,
    "sic_code":"7200"
  },
  {
    "category_id":290,
    "parent_category_id":177,
    "category_level":2,
    "title":"Publishing",
    "naic_code":511,
    "sic_code":"2700"
  },
  {
    "category_id":291,
    "parent_category_id":177,
    "category_level":2,
    "title":"Real Estate",
    "naic_code":531,
    "sic_code":"6500"
  },
  {
    "category_id":292,
    "parent_category_id":291,
    "category_level":3,
    "title":"Property Management",
    "naic_code":53131,
    "sic_code":"6530"
  },
  {
    "category_id":297,
    "parent_category_id":291,
    "category_level":3,
    "title":"Boarding Houses",
    "naic_code":72131,
    "sic_code":"7020"
  },
  {
    "category_id":348,
    "parent_category_id":347,
    "category_level":4,
    "title":"American",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":350,
    "parent_category_id":347,
    "category_level":4,
    "title":"Buffets",
    "naic_code":72251,
    "sic_code":"5812"
  },
  {
    "category_id":249,
    "parent_category_id":235,
    "category_level":3,
    "title":"Home Inspection Services",
    "naic_code":54135,
    "sic_code":null
  },
  {
    "category_id":250,
    "parent_category_id":123,
    "category_level":2,
    "title":"Housewares",
    "naic_code":4422,
    "sic_code":"5710"
  },
  {
    "category_id":255,
    "parent_category_id":291,
    "category_level":3,
    "title":"Mobile Homes",
    "naic_code":45393,
    "sic_code":"2451"
  },
  {
    "category_id":262,
    "parent_category_id":177,
    "category_level":2,
    "title":"Storage",
    "naic_code":493,
    "sic_code":"4225"
  },
  {
    "category_id":263,
    "parent_category_id":235,
    "category_level":3,
    "title":"Swimming Pool Maintenance and Services",
    "naic_code":56173,
    "sic_code":"7349"
  },
  {
    "category_id":264,
    "parent_category_id":235,
    "category_level":3,
    "title":"Tree Service",
    "naic_code":56173,
    "sic_code":"0780"
  },
  {
    "category_id":267,
    "parent_category_id":177,
    "category_level":2,
    "title":"Import and Export",
    "naic_code":42,
    "sic_code":"50"
  },
  {
    "category_id":294,
    "parent_category_id":291,
    "category_level":3,
    "title":"Real Estate Appraiser",
    "naic_code":53132,
    "sic_code":"6500"
  },
  {
    "category_id":298,
    "parent_category_id":291,
    "category_level":3,
    "title":"Building and Land Surveyors",
    "naic_code":541370,
    "sic_code":null
  },
  {
    "category_id":299,
    "parent_category_id":291,
    "category_level":3,
    "title":"Commercial Real Estate",
    "naic_code":531,
    "sic_code":"6510"
  },
  {
    "category_id":300,
    "parent_category_id":291,
    "category_level":3,
    "title":"Corporate Housing",
    "naic_code":721,
    "sic_code":"6500"
  },
  {
    "category_id":317,
    "parent_category_id":308,
    "category_level":2,
    "title":"Entertainment",
    "naic_code":71,
    "sic_code":"7929"
  },
  {
    "category_id":321,
    "parent_category_id":317,
    "category_level":3,
    "title":"Bingo",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":328,
    "parent_category_id":317,
    "category_level":3,
    "title":"Go Carts",
    "naic_code":7139,
    "sic_code":"7948"
  },
  {
    "category_id":330,
    "parent_category_id":317,
    "category_level":3,
    "title":"Karaoke",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":335,
    "parent_category_id":317,
    "category_level":3,
    "title":"Party Centers",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":338,
    "parent_category_id":308,
    "category_level":2,
    "title":"Food and Dining",
    "naic_code":722,
    "sic_code":"5800"
  },
  {
    "category_id":347,
    "parent_category_id":338,
    "category_level":3,
    "title":"Restaurants",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":354,
    "parent_category_id":347,
    "category_level":4,
    "title":"Diners",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":356,
    "parent_category_id":347,
    "category_level":4,
    "title":"French",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":387,
    "parent_category_id":372,
    "category_level":2,
    "title":"Outdoors",
    "naic_code":7139,
    "sic_code":"7030"
  },
  {
    "category_id":415,
    "parent_category_id":1,
    "category_level":1,
    "title":"Transportation",
    "naic_code":481111,
    "sic_code":"4700"
  },
  {
    "category_id":430,
    "parent_category_id":1,
    "category_level":1,
    "title":"Travel",
    "naic_code":56151,
    "sic_code":"4722"
  },
  {
    "category_id":446,
    "parent_category_id":177,
    "category_level":2,
    "title":"Career Counseling",
    "naic_code":611710,
    "sic_code":"8299"
  },
  {
    "category_id":448,
    "parent_category_id":269,
    "category_level":3,
    "title":"Notary",
    "naic_code":541199,
    "sic_code":"7389"
  },
  {
    "category_id":453,
    "parent_category_id":37,
    "category_level":3,
    "title":"Embassies",
    "naic_code":928120,
    "sic_code":"9721"
  },
  {
    "category_id":458,
    "parent_category_id":347,
    "category_level":4,
    "title":"Food Trucks",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":459,
    "parent_category_id":415,
    "category_level":2,
    "title":"Rest Areas",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":462,
    "parent_category_id":425,
    "category_level":4,
    "title":"International Airports",
    "naic_code":488119,
    "sic_code":"4581"
  },
  {
    "category_id":467,
    "parent_category_id":1,
    "category_level":1,
    "title":"NoExport",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":3,
    "parent_category_id":2,
    "category_level":2,
    "title":"Car Appraisers",
    "naic_code":null,
    "sic_code":"7540"
  },
  {
    "category_id":4,
    "parent_category_id":2,
    "category_level":2,
    "title":"Car Dealers and Leasing",
    "naic_code":441110,
    "sic_code":"5510"
  },
  {
    "category_id":5,
    "parent_category_id":4,
    "category_level":3,
    "title":"Used Cars",
    "naic_code":44112,
    "sic_code":"5520"
  },
  {
    "category_id":6,
    "parent_category_id":2,
    "category_level":2,
    "title":"Car Parts and Accessories",
    "naic_code":441310,
    "sic_code":"3714"
  },
  {
    "category_id":7,
    "parent_category_id":2,
    "category_level":2,
    "title":"Car Wash and Detail",
    "naic_code":811192,
    "sic_code":"7542"
  },
  {
    "category_id":8,
    "parent_category_id":2,
    "category_level":2,
    "title":"Classic and Antique Car",
    "naic_code":441120,
    "sic_code":"5520"
  },
  {
    "category_id":10,
    "parent_category_id":9,
    "category_level":3,
    "title":"Oil and Lube",
    "naic_code":811191,
    "sic_code":"7540"
  },
  {
    "category_id":11,
    "parent_category_id":9,
    "category_level":3,
    "title":"Smog Check",
    "naic_code":811112,
    "sic_code":"7540"
  },
  {
    "category_id":12,
    "parent_category_id":9,
    "category_level":3,
    "title":"Tires",
    "naic_code":441320,
    "sic_code":"7534"
  },
  {
    "category_id":13,
    "parent_category_id":9,
    "category_level":3,
    "title":"Transmissions",
    "naic_code":811113,
    "sic_code":"7549"
  },
  {
    "category_id":14,
    "parent_category_id":2,
    "category_level":2,
    "title":"Motorcycles, Mopeds and Scooters",
    "naic_code":44122,
    "sic_code":"5570"
  },
  {
    "category_id":15,
    "parent_category_id":14,
    "category_level":3,
    "title":"Repair",
    "naic_code":811198,
    "sic_code":"7539"
  },
  {
    "category_id":16,
    "parent_category_id":14,
    "category_level":3,
    "title":"Sales",
    "naic_code":44122,
    "sic_code":"5570"
  },
  {
    "category_id":17,
    "parent_category_id":2,
    "category_level":2,
    "title":"RVs and Motor Homes",
    "naic_code":441210,
    "sic_code":"3716"
  },
  {
    "category_id":18,
    "parent_category_id":2,
    "category_level":2,
    "title":"Salvage Yards",
    "naic_code":423140,
    "sic_code":"7549"
  },
  {
    "category_id":19,
    "parent_category_id":2,
    "category_level":2,
    "title":"Towing",
    "naic_code":488410,
    "sic_code":"7549"
  },
  {
    "category_id":21,
    "parent_category_id":20,
    "category_level":2,
    "title":"Animal Shelters and Humane Societies",
    "naic_code":813319,
    "sic_code":"0750"
  },
  {
    "category_id":23,
    "parent_category_id":20,
    "category_level":2,
    "title":"Day Care and Preschools",
    "naic_code":624410,
    "sic_code":"8290"
  },
  {
    "category_id":25,
    "parent_category_id":20,
    "category_level":2,
    "title":"Drug and Alcohol Services",
    "naic_code":621420,
    "sic_code":"8310"
  },
  {
    "category_id":27,
    "parent_category_id":26,
    "category_level":3,
    "title":"Adult Education",
    "naic_code":6115,
    "sic_code":"8290"
  },
  {
    "category_id":29,
    "parent_category_id":26,
    "category_level":3,
    "title":"Colleges and Universities",
    "naic_code":61131,
    "sic_code":"8220"
  },
  {
    "category_id":30,
    "parent_category_id":26,
    "category_level":3,
    "title":"Computer Training",
    "naic_code":611420,
    "sic_code":"8240"
  },
  {
    "category_id":31,
    "parent_category_id":26,
    "category_level":3,
    "title":"Culinary Lessons and Schools",
    "naic_code":6116,
    "sic_code":"8290"
  },
  {
    "category_id":32,
    "parent_category_id":26,
    "category_level":3,
    "title":"Driving Schools",
    "naic_code":611692,
    "sic_code":"8290"
  },
  {
    "category_id":35,
    "parent_category_id":26,
    "category_level":3,
    "title":"Tutoring and Educational Services",
    "naic_code":611691,
    "sic_code":"8200"
  },
  {
    "category_id":22,
    "parent_category_id":20,
    "category_level":2,
    "title":"Cemeteries",
    "naic_code":812220,
    "sic_code":"7260"
  },
  {
    "category_id":24,
    "parent_category_id":20,
    "category_level":2,
    "title":"Disabled Persons Services",
    "naic_code":62412,
    "sic_code":"8310"
  },
  {
    "category_id":33,
    "parent_category_id":26,
    "category_level":3,
    "title":"Fraternities and Sororities",
    "naic_code":721310,
    "sic_code":"7020"
  },
  {
    "category_id":76,
    "parent_category_id":62,
    "category_level":2,
    "title":"Mental Health",
    "naic_code":62133,
    "sic_code":"8090"
  },
  {
    "category_id":77,
    "parent_category_id":76,
    "category_level":3,
    "title":"Counseling and Therapy",
    "naic_code":62133,
    "sic_code":"8090"
  },
  {
    "category_id":78,
    "parent_category_id":76,
    "category_level":3,
    "title":"Psychologists",
    "naic_code":62133,
    "sic_code":"8090"
  },
  {
    "category_id":79,
    "parent_category_id":62,
    "category_level":2,
    "title":"Nurses",
    "naic_code":6219,
    "sic_code":"8090"
  },
  {
    "category_id":80,
    "parent_category_id":62,
    "category_level":2,
    "title":"Pharmacies",
    "naic_code":446110,
    "sic_code":"8090"
  },
  {
    "category_id":81,
    "parent_category_id":62,
    "category_level":2,
    "title":"Physical Therapy and Rehabilitation",
    "naic_code":62139,
    "sic_code":"8090"
  },
  {
    "category_id":82,
    "parent_category_id":81,
    "category_level":3,
    "title":"Sports Medicine",
    "naic_code":62139,
    "sic_code":"8090"
  },
  {
    "category_id":93,
    "parent_category_id":83,
    "category_level":3,
    "title":"Obstetricians and Gynecologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":94,
    "parent_category_id":83,
    "category_level":3,
    "title":"Oncologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":96,
    "parent_category_id":83,
    "category_level":3,
    "title":"Orthopedic Surgeons",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":97,
    "parent_category_id":83,
    "category_level":3,
    "title":"Pathologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":98,
    "parent_category_id":83,
    "category_level":3,
    "title":"Pediatricians",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":125,
    "parent_category_id":123,
    "category_level":2,
    "title":"Antiques",
    "naic_code":453,
    "sic_code":"5990"
  },
  {
    "category_id":126,
    "parent_category_id":123,
    "category_level":2,
    "title":"Arts and Crafts",
    "naic_code":453,
    "sic_code":"5940"
  },
  {
    "category_id":127,
    "parent_category_id":123,
    "category_level":2,
    "title":"Auctions",
    "naic_code":454112,
    "sic_code":"5960"
  },
  {
    "category_id":128,
    "parent_category_id":123,
    "category_level":2,
    "title":"Beauty Products",
    "naic_code":44612,
    "sic_code":"5990"
  },
  {
    "category_id":130,
    "parent_category_id":123,
    "category_level":2,
    "title":"Bookstores",
    "naic_code":451211,
    "sic_code":"5942"
  },
  {
    "category_id":144,
    "parent_category_id":142,
    "category_level":3,
    "title":"Jewelry and Watches",
    "naic_code":44831,
    "sic_code":"5944"
  },
  {
    "category_id":145,
    "parent_category_id":142,
    "category_level":3,
    "title":"Shoes",
    "naic_code":44821,
    "sic_code":"5660"
  },
  {
    "category_id":129,
    "parent_category_id":123,
    "category_level":2,
    "title":"Bicycles",
    "naic_code":45111,
    "sic_code":"5941"
  },
  {
    "category_id":36,
    "parent_category_id":26,
    "category_level":3,
    "title":"Vocational Schools",
    "naic_code":611519,
    "sic_code":"8240"
  },
  {
    "category_id":37,
    "parent_category_id":20,
    "category_level":2,
    "title":"Government Departments and Agencies",
    "naic_code":9211,
    "sic_code":null
  },
  {
    "category_id":39,
    "parent_category_id":20,
    "category_level":2,
    "title":"Housing Assistance and Shelters",
    "naic_code":925,
    "sic_code":null
  },
  {
    "category_id":41,
    "parent_category_id":40,
    "category_level":3,
    "title":"Rescue Services",
    "naic_code":92219,
    "sic_code":null
  },
  {
    "category_id":42,
    "parent_category_id":40,
    "category_level":3,
    "title":"Fire Stations",
    "naic_code":92216,
    "sic_code":null
  },
  {
    "category_id":43,
    "parent_category_id":40,
    "category_level":3,
    "title":"Police Stations",
    "naic_code":92212,
    "sic_code":null
  },
  {
    "category_id":44,
    "parent_category_id":20,
    "category_level":2,
    "title":"Libraries",
    "naic_code":519120,
    "sic_code":"8230"
  },
  {
    "category_id":45,
    "parent_category_id":20,
    "category_level":2,
    "title":"Military",
    "naic_code":9281,
    "sic_code":null
  },
  {
    "category_id":46,
    "parent_category_id":45,
    "category_level":3,
    "title":"Bases",
    "naic_code":9281,
    "sic_code":null
  },
  {
    "category_id":48,
    "parent_category_id":47,
    "category_level":3,
    "title":"Charities and Non-Profits",
    "naic_code":813,
    "sic_code":"8690"
  },
  {
    "category_id":49,
    "parent_category_id":47,
    "category_level":3,
    "title":"Environmental",
    "naic_code":8133,
    "sic_code":"8650"
  },
  {
    "category_id":50,
    "parent_category_id":47,
    "category_level":3,
    "title":"Youth Organizations",
    "naic_code":81399,
    "sic_code":"8640"
  },
  {
    "category_id":51,
    "parent_category_id":20,
    "category_level":2,
    "title":"Post Offices",
    "naic_code":491110,
    "sic_code":null
  },
  {
    "category_id":54,
    "parent_category_id":53,
    "category_level":3,
    "title":"Buddhist Temples",
    "naic_code":8131,
    "sic_code":"8660"
  },
  {
    "category_id":55,
    "parent_category_id":53,
    "category_level":3,
    "title":"Churches",
    "naic_code":8131,
    "sic_code":"8660"
  },
  {
    "category_id":56,
    "parent_category_id":53,
    "category_level":3,
    "title":"Hindu Temples",
    "naic_code":8131,
    "sic_code":"8660"
  },
  {
    "category_id":57,
    "parent_category_id":53,
    "category_level":3,
    "title":"Mosques",
    "naic_code":8131,
    "sic_code":"8660"
  },
  {
    "category_id":58,
    "parent_category_id":53,
    "category_level":3,
    "title":"Synagogues",
    "naic_code":8131,
    "sic_code":"8660"
  },
  {
    "category_id":59,
    "parent_category_id":20,
    "category_level":2,
    "title":"Senior Citizen Services",
    "naic_code":62412,
    "sic_code":"8310"
  },
  {
    "category_id":60,
    "parent_category_id":59,
    "category_level":3,
    "title":"Retirement",
    "naic_code":62331,
    "sic_code":"8310"
  },
  {
    "category_id":61,
    "parent_category_id":20,
    "category_level":2,
    "title":"Utility Companies",
    "naic_code":221,
    "sic_code":"4900"
  },
  {
    "category_id":63,
    "parent_category_id":62,
    "category_level":2,
    "title":"AIDS Resources",
    "naic_code":6219,
    "sic_code":"8090"
  },
  {
    "category_id":64,
    "parent_category_id":62,
    "category_level":2,
    "title":"Assisted Living Services",
    "naic_code":623312,
    "sic_code":"8050"
  },
  {
    "category_id":65,
    "parent_category_id":62,
    "category_level":2,
    "title":"Home Health Care Services",
    "naic_code":62412,
    "sic_code":"8360"
  },
  {
    "category_id":66,
    "parent_category_id":64,
    "category_level":3,
    "title":"Facilities and Nursing Homes",
    "naic_code":623,
    "sic_code":"8050"
  },
  {
    "category_id":67,
    "parent_category_id":62,
    "category_level":2,
    "title":"Blood Banks and Centers",
    "naic_code":621991,
    "sic_code":"8090"
  },
  {
    "category_id":68,
    "parent_category_id":62,
    "category_level":2,
    "title":"Chiropractors",
    "naic_code":62131,
    "sic_code":"8041"
  },
  {
    "category_id":115,
    "parent_category_id":112,
    "category_level":3,
    "title":"Forests",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":121,
    "parent_category_id":118,
    "category_level":3,
    "title":"Playgrounds",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":122,
    "parent_category_id":118,
    "category_level":3,
    "title":"Urban Parks",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":124,
    "parent_category_id":123,
    "category_level":2,
    "title":"Adult",
    "naic_code":453,
    "sic_code":"5990"
  },
  {
    "category_id":131,
    "parent_category_id":123,
    "category_level":2,
    "title":"Cards and Stationery",
    "naic_code":453210,
    "sic_code":"5943"
  },
  {
    "category_id":134,
    "parent_category_id":133,
    "category_level":3,
    "title":"Cameras",
    "naic_code":443142,
    "sic_code":"5946"
  },
  {
    "category_id":135,
    "parent_category_id":133,
    "category_level":3,
    "title":"Mobile Phones",
    "naic_code":33421,
    "sic_code":"3661"
  },
  {
    "category_id":190,
    "parent_category_id":177,
    "category_level":2,
    "title":"Textiles",
    "naic_code":313,
    "sic_code":"2200"
  },
  {
    "category_id":117,
    "parent_category_id":112,
    "category_level":3,
    "title":"Rivers",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":119,
    "parent_category_id":118,
    "category_level":3,
    "title":"Natural Parks",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":116,
    "parent_category_id":112,
    "category_level":3,
    "title":"Lakes",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":69,
    "parent_category_id":62,
    "category_level":2,
    "title":"Dentists",
    "naic_code":6212,
    "sic_code":"8020"
  },
  {
    "category_id":71,
    "parent_category_id":70,
    "category_level":3,
    "title":"Ambulance",
    "naic_code":62191,
    "sic_code":"8090"
  },
  {
    "category_id":73,
    "parent_category_id":72,
    "category_level":3,
    "title":"Acupuncture",
    "naic_code":6213,
    "sic_code":"8040"
  },
  {
    "category_id":74,
    "parent_category_id":62,
    "category_level":2,
    "title":"Hospitals, Clinics and Medical Centers",
    "naic_code":622,
    "sic_code":"8060"
  },
  {
    "category_id":75,
    "parent_category_id":62,
    "category_level":2,
    "title":"Medical Supplies and Labs",
    "naic_code":33911,
    "sic_code":"3840"
  },
  {
    "category_id":84,
    "parent_category_id":83,
    "category_level":3,
    "title":"Anesthesiologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":85,
    "parent_category_id":83,
    "category_level":3,
    "title":"Cardiologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":86,
    "parent_category_id":83,
    "category_level":3,
    "title":"Dermatologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":87,
    "parent_category_id":83,
    "category_level":3,
    "title":"Ear, Nose and Throat",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":88,
    "parent_category_id":83,
    "category_level":3,
    "title":"Family Medicine",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":90,
    "parent_category_id":83,
    "category_level":3,
    "title":"General Surgery",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":91,
    "parent_category_id":83,
    "category_level":3,
    "title":"Internal Medicine",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":92,
    "parent_category_id":83,
    "category_level":3,
    "title":"Neurologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":99,
    "parent_category_id":83,
    "category_level":3,
    "title":"Plastic Surgeons",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":100,
    "parent_category_id":83,
    "category_level":3,
    "title":"Psychiatrists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":101,
    "parent_category_id":83,
    "category_level":3,
    "title":"Radiologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":102,
    "parent_category_id":83,
    "category_level":3,
    "title":"Respiratory",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":103,
    "parent_category_id":83,
    "category_level":3,
    "title":"Urologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":104,
    "parent_category_id":62,
    "category_level":2,
    "title":"Podiatrists",
    "naic_code":621391,
    "sic_code":"8040"
  },
  {
    "category_id":89,
    "parent_category_id":83,
    "category_level":3,
    "title":"Gastroenterologists",
    "naic_code":62139,
    "sic_code":"8040"
  },
  {
    "category_id":105,
    "parent_category_id":62,
    "category_level":2,
    "title":"Pregnancy and Sexual Health",
    "naic_code":6219,
    "sic_code":"8040"
  },
  {
    "category_id":106,
    "parent_category_id":62,
    "category_level":2,
    "title":"Weight Loss and Nutritionists",
    "naic_code":812191,
    "sic_code":"8040"
  },
  {
    "category_id":108,
    "parent_category_id":107,
    "category_level":2,
    "title":"Buildings and Structures",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":109,
    "parent_category_id":107,
    "category_level":2,
    "title":"Gardens",
    "naic_code":71213,
    "sic_code":"8420"
  },
  {
    "category_id":111,
    "parent_category_id":107,
    "category_level":2,
    "title":"Monuments and Memorials",
    "naic_code":7121,
    "sic_code":null
  },
  {
    "category_id":113,
    "parent_category_id":112,
    "category_level":3,
    "title":"Beaches",
    "naic_code":71219,
    "sic_code":"7999"
  },
  {
    "category_id":165,
    "parent_category_id":123,
    "category_level":2,
    "title":"Outlet",
    "naic_code":4539,
    "sic_code":"5990"
  },
  {
    "category_id":187,
    "parent_category_id":177,
    "category_level":2,
    "title":"Scientific",
    "naic_code":5417,
    "sic_code":"3810"
  },
  {
    "category_id":192,
    "parent_category_id":177,
    "category_level":2,
    "title":"Welding",
    "naic_code":333992,
    "sic_code":"3623"
  },
  {
    "category_id":200,
    "parent_category_id":193,
    "category_level":3,
    "title":"Promotional Items",
    "naic_code":54189,
    "sic_code":"7319"
  },
  {
    "category_id":204,
    "parent_category_id":177,
    "category_level":2,
    "title":"Agriculture and Forestry",
    "naic_code":11,
    "sic_code":"07"
  },
  {
    "category_id":205,
    "parent_category_id":177,
    "category_level":2,
    "title":"Art Restoration",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":212,
    "parent_category_id":177,
    "category_level":2,
    "title":"Employment Agencies",
    "naic_code":561311,
    "sic_code":"7361"
  },
  {
    "category_id":215,
    "parent_category_id":214,
    "category_level":3,
    "title":"Media",
    "naic_code":515,
    "sic_code":null
  },
  {
    "category_id":216,
    "parent_category_id":177,
    "category_level":2,
    "title":"Equipment Rental",
    "naic_code":5324,
    "sic_code":"7394"
  },
  {
    "category_id":220,
    "parent_category_id":219,
    "category_level":3,
    "title":"Accounting and Bookkeeping",
    "naic_code":54121,
    "sic_code":"8930"
  },
  {
    "category_id":224,
    "parent_category_id":219,
    "category_level":3,
    "title":"Collections",
    "naic_code":561440,
    "sic_code":"7320"
  },
  {
    "category_id":226,
    "parent_category_id":219,
    "category_level":3,
    "title":"Fund Raising",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":229,
    "parent_category_id":219,
    "category_level":3,
    "title":"Student Aid and Grants",
    "naic_code":522291,
    "sic_code":"6140"
  },
  {
    "category_id":231,
    "parent_category_id":230,
    "category_level":3,
    "title":"Catering",
    "naic_code":72232,
    "sic_code":null
  },
  {
    "category_id":233,
    "parent_category_id":177,
    "category_level":2,
    "title":"Funeral Services",
    "naic_code":81221,
    "sic_code":"7260"
  },
  {
    "category_id":234,
    "parent_category_id":177,
    "category_level":2,
    "title":"Geological",
    "naic_code":541330,
    "sic_code":"8910"
  },
  {
    "category_id":136,
    "parent_category_id":133,
    "category_level":3,
    "title":"Video Games",
    "naic_code":45112,
    "sic_code":"3944"
  },
  {
    "category_id":139,
    "parent_category_id":123,
    "category_level":2,
    "title":"Costumes",
    "naic_code":4539,
    "sic_code":"5690"
  },
  {
    "category_id":140,
    "parent_category_id":123,
    "category_level":2,
    "title":"Dance and Music",
    "naic_code":4539,
    "sic_code":"5733"
  },
  {
    "category_id":141,
    "parent_category_id":123,
    "category_level":2,
    "title":"Department Stores",
    "naic_code":45211,
    "sic_code":"5310"
  },
  {
    "category_id":156,
    "parent_category_id":149,
    "category_level":3,
    "title":"Kosher",
    "naic_code":4452,
    "sic_code":"2099"
  },
  {
    "category_id":159,
    "parent_category_id":123,
    "category_level":2,
    "title":"Glasses",
    "naic_code":4539,
    "sic_code":"5690"
  },
  {
    "category_id":167,
    "parent_category_id":123,
    "category_level":2,
    "title":"Pets",
    "naic_code":453910,
    "sic_code":"5940"
  },
  {
    "category_id":171,
    "parent_category_id":123,
    "category_level":2,
    "title":"Supermarkets and Groceries",
    "naic_code":445110,
    "sic_code":"5410"
  },
  {
    "category_id":172,
    "parent_category_id":123,
    "category_level":2,
    "title":"Tobacco",
    "naic_code":453991,
    "sic_code":"5993"
  },
  {
    "category_id":173,
    "parent_category_id":123,
    "category_level":2,
    "title":"Toys",
    "naic_code":45112,
    "sic_code":"5945"
  },
  {
    "category_id":174,
    "parent_category_id":123,
    "category_level":2,
    "title":"Vintage and Thrift",
    "naic_code":44112,
    "sic_code":"5930"
  },
  {
    "category_id":176,
    "parent_category_id":123,
    "category_level":2,
    "title":"Wedding and Bridal",
    "naic_code":4539,
    "sic_code":"5999"
  },
  {
    "category_id":181,
    "parent_category_id":177,
    "category_level":2,
    "title":"Metals",
    "naic_code":332,
    "sic_code":"3300"
  },
  {
    "category_id":184,
    "parent_category_id":177,
    "category_level":2,
    "title":"Plastics",
    "naic_code":3261,
    "sic_code":"2821"
  },
  {
    "category_id":188,
    "parent_category_id":177,
    "category_level":2,
    "title":"Security and Safety",
    "naic_code":5616,
    "sic_code":null
  },
  {
    "category_id":191,
    "parent_category_id":177,
    "category_level":2,
    "title":"Water and Waste Management",
    "naic_code":562,
    "sic_code":"4940"
  },
  {
    "category_id":201,
    "parent_category_id":193,
    "category_level":3,
    "title":"Public Relations",
    "naic_code":541820,
    "sic_code":"7392"
  },
  {
    "category_id":235,
    "parent_category_id":177,
    "category_level":2,
    "title":"Home Improvement",
    "naic_code":238,
    "sic_code":"1510"
  },
  {
    "category_id":143,
    "parent_category_id":142,
    "category_level":3,
    "title":"Clothing and Accessories",
    "naic_code":448,
    "sic_code":"5600"
  },
  {
    "category_id":158,
    "parent_category_id":123,
    "category_level":2,
    "title":"Gift and Novelty",
    "naic_code":45322,
    "sic_code":"5947"
  },
  {
    "category_id":179,
    "parent_category_id":177,
    "category_level":2,
    "title":"Industrial Machinery and Vehicles",
    "naic_code":333,
    "sic_code":"3560"
  },
  {
    "category_id":182,
    "parent_category_id":177,
    "category_level":2,
    "title":"Packaging",
    "naic_code":56191,
    "sic_code":null
  },
  {
    "category_id":146,
    "parent_category_id":142,
    "category_level":3,
    "title":"Swimwear",
    "naic_code":45111,
    "sic_code":"5690"
  },
  {
    "category_id":147,
    "parent_category_id":123,
    "category_level":2,
    "title":"Flea Markets",
    "naic_code":4533,
    "sic_code":"5930"
  },
  {
    "category_id":148,
    "parent_category_id":123,
    "category_level":2,
    "title":"Florists",
    "naic_code":4531,
    "sic_code":"5992"
  },
  {
    "category_id":150,
    "parent_category_id":149,
    "category_level":3,
    "title":"Beer, Wine and Spirits",
    "naic_code":44531,
    "sic_code":"5920"
  },
  {
    "category_id":152,
    "parent_category_id":149,
    "category_level":3,
    "title":"Cheese",
    "naic_code":311513,
    "sic_code":"2022"
  },
  {
    "category_id":153,
    "parent_category_id":149,
    "category_level":3,
    "title":"Chocolate",
    "naic_code":31135,
    "sic_code":"2066"
  },
  {
    "category_id":154,
    "parent_category_id":149,
    "category_level":3,
    "title":"Farmers' Markets",
    "naic_code":445230,
    "sic_code":"5430"
  },
  {
    "category_id":162,
    "parent_category_id":123,
    "category_level":2,
    "title":"Music, Video and DVD",
    "naic_code":4539,
    "sic_code":"5733"
  },
  {
    "category_id":163,
    "parent_category_id":123,
    "category_level":2,
    "title":"Newsstands",
    "naic_code":451212,
    "sic_code":"5994"
  },
  {
    "category_id":164,
    "parent_category_id":123,
    "category_level":2,
    "title":"Nurseries and Garden Centers",
    "naic_code":44422,
    "sic_code":"5260"
  },
  {
    "category_id":168,
    "parent_category_id":123,
    "category_level":2,
    "title":"Photos and Frames",
    "naic_code":4539,
    "sic_code":"5946"
  },
  {
    "category_id":169,
    "parent_category_id":123,
    "category_level":2,
    "title":"Shopping Centers and Malls",
    "naic_code":4539,
    "sic_code":"5990"
  },
  {
    "category_id":170,
    "parent_category_id":123,
    "category_level":2,
    "title":"Sporting Goods",
    "naic_code":45111,
    "sic_code":"5941"
  },
  {
    "category_id":175,
    "parent_category_id":123,
    "category_level":2,
    "title":"Warehouses and Wholesale Stores",
    "naic_code":4539,
    "sic_code":"5999"
  },
  {
    "category_id":178,
    "parent_category_id":177,
    "category_level":2,
    "title":"Business and Strategy Consulting",
    "naic_code":54161,
    "sic_code":"7300"
  },
  {
    "category_id":180,
    "parent_category_id":177,
    "category_level":2,
    "title":"Logging and Sawmills",
    "naic_code":113,
    "sic_code":"2420"
  },
  {
    "category_id":183,
    "parent_category_id":177,
    "category_level":2,
    "title":"Petroleum",
    "naic_code":3241,
    "sic_code":"2900"
  },
  {
    "category_id":185,
    "parent_category_id":177,
    "category_level":2,
    "title":"Refrigeration and Ice",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":186,
    "parent_category_id":177,
    "category_level":2,
    "title":"Rubber",
    "naic_code":3262,
    "sic_code":"3000"
  },
  {
    "category_id":189,
    "parent_category_id":177,
    "category_level":2,
    "title":"Telecommunication Services",
    "naic_code":517,
    "sic_code":"4810"
  },
  {
    "category_id":157,
    "parent_category_id":123,
    "category_level":2,
    "title":"Furniture and Decor",
    "naic_code":442,
    "sic_code":"5700"
  },
  {
    "category_id":151,
    "parent_category_id":149,
    "category_level":3,
    "title":"Candy Stores",
    "naic_code":445292,
    "sic_code":"5440"
  },
  {
    "category_id":194,
    "parent_category_id":193,
    "category_level":3,
    "title":"Advertising Agencies and Media Buyers",
    "naic_code":54181,
    "sic_code":"7311"
  },
  {
    "category_id":195,
    "parent_category_id":193,
    "category_level":3,
    "title":"Creative Services",
    "naic_code":54181,
    "sic_code":"7319"
  },
  {
    "category_id":196,
    "parent_category_id":193,
    "category_level":3,
    "title":"Direct Mail and Email Marketing Services",
    "naic_code":54186,
    "sic_code":"7331"
  },
  {
    "category_id":197,
    "parent_category_id":193,
    "category_level":3,
    "title":"Market Research and Consulting",
    "naic_code":54191,
    "sic_code":"7319"
  },
  {
    "category_id":198,
    "parent_category_id":193,
    "category_level":3,
    "title":"Online Advertising",
    "naic_code":541890,
    "sic_code":"7319"
  },
  {
    "category_id":199,
    "parent_category_id":193,
    "category_level":3,
    "title":"Print, TV, Radio and Outdoor Advertising",
    "naic_code":541850,
    "sic_code":"7310"
  },
  {
    "category_id":206,
    "parent_category_id":177,
    "category_level":2,
    "title":"Audiovisual",
    "naic_code":512,
    "sic_code":null
  },
  {
    "category_id":207,
    "parent_category_id":177,
    "category_level":2,
    "title":"Automation and Control Systems",
    "naic_code":334519,
    "sic_code":"3622"
  },
  {
    "category_id":211,
    "parent_category_id":177,
    "category_level":2,
    "title":"Electrical Equipment",
    "naic_code":3353,
    "sic_code":"3600"
  },
  {
    "category_id":213,
    "parent_category_id":177,
    "category_level":2,
    "title":"Engineering",
    "naic_code":541330,
    "sic_code":"8910"
  },
  {
    "category_id":218,
    "parent_category_id":221,
    "category_level":4,
    "title":"ATMs",
    "naic_code":522,
    "sic_code":"6000"
  },
  {
    "category_id":221,
    "parent_category_id":219,
    "category_level":3,
    "title":"Banking and Finance",
    "naic_code":522,
    "sic_code":"6000"
  },
  {
    "category_id":222,
    "parent_category_id":219,
    "category_level":3,
    "title":"Business Brokers and Franchises",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":223,
    "parent_category_id":219,
    "category_level":3,
    "title":"Check Cashing",
    "naic_code":522291,
    "sic_code":"6140"
  },
  {
    "category_id":227,
    "parent_category_id":219,
    "category_level":3,
    "title":"Loans and Mortgages",
    "naic_code":52231,
    "sic_code":"6160"
  },
  {
    "category_id":228,
    "parent_category_id":219,
    "category_level":3,
    "title":"Stock Brokers",
    "naic_code":523120,
    "sic_code":"6210"
  },
  {
    "category_id":314,
    "parent_category_id":312,
    "category_level":3,
    "title":"Jazz and Blues Cafes",
    "naic_code":7224,
    "sic_code":"5813"
  },
  {
    "category_id":202,
    "parent_category_id":193,
    "category_level":3,
    "title":"Search Engine Marketing and Optimization",
    "naic_code":54189,
    "sic_code":"7319"
  },
  {
    "category_id":203,
    "parent_category_id":193,
    "category_level":3,
    "title":"Writing, Copywriting and Technical Writing",
    "naic_code":54189,
    "sic_code":"7319"
  },
  {
    "category_id":209,
    "parent_category_id":177,
    "category_level":2,
    "title":"Computers",
    "naic_code":5415,
    "sic_code":"7370"
  },
  {
    "category_id":217,
    "parent_category_id":177,
    "category_level":2,
    "title":"Events and Event Planning",
    "naic_code":null,
    "sic_code":null
  },
  {
    "category_id":329,
    "parent_category_id":317,
    "category_level":3,
    "title":"Hookah Lounges",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":331,
    "parent_category_id":317,
    "category_level":3,
    "title":"Miniature Golf",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":332,
    "parent_category_id":317,
    "category_level":3,
    "title":"Movie Theatres",
    "naic_code":512131,
    "sic_code":"7830"
  },
  {
    "category_id":333,
    "parent_category_id":317,
    "category_level":3,
    "title":"Music and Show Venues",
    "naic_code":71113,
    "sic_code":"7920"
  },
  {
    "category_id":334,
    "parent_category_id":317,
    "category_level":3,
    "title":"Night Clubs",
    "naic_code":7224,
    "sic_code":"7910"
  },
  {
    "category_id":336,
    "parent_category_id":317,
    "category_level":3,
    "title":"Psychics and Astrologers",
    "naic_code":7139,
    "sic_code":"7929"
  },
  {
    "category_id":337,
    "parent_category_id":317,
    "category_level":3,
    "title":"Ticket Sales",
    "naic_code":711,
    "sic_code":"7999"
  },
  {
    "category_id":339,
    "parent_category_id":338,
    "category_level":3,
    "title":"Bagels and Donuts",
    "naic_code":72251,
    "sic_code":"5812"
  },
  {
    "category_id":441,
    "parent_category_id":83,
    "category_level":3,
    "title":"Geriatrics",
    "naic_code":62139,
    "sic_code":"8049"
  },
  {
    "category_id":443,
    "parent_category_id":149,
    "category_level":3,
    "title":"Meat and Seafood",
    "naic_code":44522,
    "sic_code":"5146"
  },
  {
    "category_id":444,
    "parent_category_id":123,
    "category_level":2,
    "title":"Office Supplies",
    "naic_code":45321,
    "sic_code":"5112"
  },
  {
    "category_id":435,
    "parent_category_id":432,
    "category_level":3,
    "title":"Hostels",
    "naic_code":721199,
    "sic_code":"7000"
  },
  {
    "category_id":442,
    "parent_category_id":123,
    "category_level":2,
    "title":"Discount Stores",
    "naic_code":45299,
    "sic_code":"5531"
  },
  {
    "category_id":248,
    "parent_category_id":123,
    "category_level":2,
    "title":"Home Appliances",
    "naic_code":443141,
    "sic_code":"3630"
  },
  {
    "category_id":256,
    "parent_category_id":235,
    "category_level":3,
    "title":"Movers",
    "naic_code":48421,
    "sic_code":"4780"
  },
  {
    "category_id":320,
    "parent_category_id":317,
    "category_level":3,
    "title":"Billiard and Pool",
    "naic_code":7139,
    "sic_code":"7932"
  },
  {
    "category_id":244,
    "parent_category_id":235,
    "category_level":3,
    "title":"Electricians",
    "naic_code":23821,
    "sic_code":"1730"
  },
  {
    "category_id":245,
    "parent_category_id":235,
    "category_level":3,
    "title":"Fences, Fireplaces and Garage Doors",
    "naic_code":2389,
    "sic_code":"1700"
  },
  {
    "category_id":246,
    "parent_category_id":235,
    "category_level":3,
    "title":"Hardware and Services",
    "naic_code":44413,
    "sic_code":"5250"
  },
  {
    "category_id":253,
    "parent_category_id":235,
    "category_level":3,
    "title":"Landscaping and Gardeners",
    "naic_code":561730,
    "sic_code":"0780"
  },
  {
    "category_id":254,
    "parent_category_id":235,
    "category_level":3,
    "title":"Lighting Fixtures",
    "naic_code":33512,
    "sic_code":"3645"
  },
  {
    "category_id":257,
    "parent_category_id":235,
    "category_level":3,
    "title":"Painting",
    "naic_code":23832,
    "sic_code":"1720"
  },
  {
    "category_id":258,
    "parent_category_id":235,
    "category_level":3,
    "title":"Pest Control",
    "naic_code":56171,
    "sic_code":"7349"
  },
  {
    "category_id":259,
    "parent_category_id":235,
    "category_level":3,
    "title":"Plumbing",
    "naic_code":23822,
    "sic_code":"1710"
  },
  {
    "category_id":266,
    "parent_category_id":177,
    "category_level":2,
    "title":"Human Resources",
    "naic_code":541612,
    "sic_code":"7300"
  },
  {
    "category_id":293,
    "parent_category_id":291,
    "category_level":3,
    "title":"Real Estate Agents",
    "naic_code":53121,
    "sic_code":"6530"
  },
  {
    "category_id":295,
    "parent_category_id":291,
    "category_level":3,
    "title":"Real Estate Development and Title Companies",
    "naic_code":5313,
    "sic_code":"6540"
  },
  {
    "category_id":296,
    "parent_category_id":291,
    "category_level":3,
    "title":"Apartments, Condos, and Houses",
    "naic_code":721,
    "sic_code":"6500"
  },
  {
    "category_id":302,
    "parent_category_id":177,
    "category_level":2,
    "title":"Repair Services",
    "naic_code":811,
    "sic_code":"7600"
  },
  {
    "category_id":303,
    "parent_category_id":177,
    "category_level":2,
    "title":"Shipping, Freight, and Material Transportation",
    "naic_code":4885,
    "sic_code":"4723"
  },
  {
    "category_id":304,
    "parent_category_id":177,
    "category_level":2,
    "title":"Tailors",
    "naic_code":31521,
    "sic_code":null
  },
  {
    "category_id":305,
    "parent_category_id":177,
    "category_level":2,
    "title":"Veterinarians",
    "naic_code":541940,
    "sic_code":"0740"
  },
  {
    "category_id":306,
    "parent_category_id":460,
    "category_level":3,
    "title":"Web Design and Development",
    "naic_code":541511,
    "sic_code":"7379"
  },
  {
    "category_id":307,
    "parent_category_id":177,
    "category_level":2,
    "title":"Wholesale",
    "naic_code":42,
    "sic_code":"50"
  },
  {
    "category_id":310,
    "parent_category_id":309,
    "category_level":3,
    "title":"Art Dealers and Galleries",
    "naic_code":453920,
    "sic_code":"8410"
  },
  {
    "category_id":311,
    "parent_category_id":309,
    "category_level":3,
    "title":"Museums",
    "naic_code":71211,
    "sic_code":"8410"
  },
  {
    "category_id":312,
    "parent_category_id":308,
    "category_level":2,
    "title":"Bars",
    "naic_code":7224,
    "sic_code":"5813"
  },
  {
    "category_id":313,
    "parent_category_id":312,
    "category_level":3,
    "title":"Hotel Lounges",
    "naic_code":7224,
    "sic_code":"5813"
  },
  {
    "category_id":315,
    "parent_category_id":312,
    "category_level":3,
    "title":"Sports Bars",
    "naic_code":7224,
    "sic_code":"5813"
  },
  {
    "category_id":316,
    "parent_category_id":312,
    "category_level":3,
    "title":"Wine Bars",
    "naic_code":7224,
    "sic_code":"5813"
  },
  {
    "category_id":318,
    "parent_category_id":317,
    "category_level":3,
    "title":"Adult Entertainment",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":319,
    "parent_category_id":317,
    "category_level":3,
    "title":"Amusement Parks",
    "naic_code":7131,
    "sic_code":"7996"
  },
  {
    "category_id":269,
    "parent_category_id":177,
    "category_level":2,
    "title":"Legal",
    "naic_code":5411,
    "sic_code":"8100"
  },
  {
    "category_id":270,
    "parent_category_id":269,
    "category_level":3,
    "title":"Credit Counseling and Bankruptcy Services",
    "naic_code":522390,
    "sic_code":null
  },
  {
    "category_id":271,
    "parent_category_id":269,
    "category_level":3,
    "title":"Immigration",
    "naic_code":928120,
    "sic_code":null
  },
  {
    "category_id":272,
    "parent_category_id":177,
    "category_level":2,
    "title":"Insurance",
    "naic_code":524,
    "sic_code":"6400"
  },
  {
    "category_id":278,
    "parent_category_id":277,
    "category_level":3,
    "title":"Dry Cleaning, Ironing and Laundry",
    "naic_code":8123,
    "sic_code":"7210"
  },
  {
    "category_id":279,
    "parent_category_id":277,
    "category_level":3,
    "title":"Hair Removal",
    "naic_code":81211,
    "sic_code":"7200"
  },
  {
    "category_id":280,
    "parent_category_id":277,
    "category_level":3,
    "title":"Beauty Salons and Barbers",
    "naic_code":812112,
    "sic_code":"7230"
  },
  {
    "category_id":281,
    "parent_category_id":277,
    "category_level":3,
    "title":"Manicures and Pedicures",
    "naic_code":812113,
    "sic_code":"7200"
  },
  {
    "category_id":282,
    "parent_category_id":277,
    "category_level":3,
    "title":"Massage Clinics and Therapists",
    "naic_code":81219,
    "sic_code":"7200"
  },
  {
    "category_id":283,
    "parent_category_id":277,
    "category_level":3,
    "title":"Piercing",
    "naic_code":81219,
    "sic_code":"7200"
  },
  {
    "category_id":284,
    "parent_category_id":277,
    "category_level":3,
    "title":"Skin Care",
    "naic_code":81211,
    "sic_code":"7200"
  },
  {
    "category_id":285,
    "parent_category_id":277,
    "category_level":3,
    "title":"Spas",
    "naic_code":81219,
    "sic_code":"7200"
  },
  {
    "category_id":286,
    "parent_category_id":277,
    "category_level":3,
    "title":"Tanning Salons",
    "naic_code":81219,
    "sic_code":"7200"
  },
  {
    "category_id":287,
    "parent_category_id":277,
    "category_level":3,
    "title":"Tattooing",
    "naic_code":81219,
    "sic_code":"7200"
  },
  {
    "category_id":289,
    "parent_category_id":177,
    "category_level":2,
    "title":"Professional Cleaning",
    "naic_code":561720,
    "sic_code":"7340"
  },
  {
    "category_id":301,
    "parent_category_id":177,
    "category_level":2,
    "title":"Renewable Energy",
    "naic_code":22111,
    "sic_code":null
  },
  {
    "category_id":276,
    "parent_category_id":177,
    "category_level":2,
    "title":"Paper",
    "naic_code":322,
    "sic_code":"5110"
  },
  {
    "category_id":309,
    "parent_category_id":308,
    "category_level":2,
    "title":"Arts",
    "naic_code":7111,
    "sic_code":"8410"
  },
  {
    "category_id":288,
    "parent_category_id":177,
    "category_level":2,
    "title":"Printing, Copying and Signage",
    "naic_code":561439,
    "sic_code":"2750"
  },
  {
    "category_id":322,
    "parent_category_id":317,
    "category_level":3,
    "title":"Bowling",
    "naic_code":71395,
    "sic_code":"7933"
  },
  {
    "category_id":343,
    "parent_category_id":338,
    "category_level":3,
    "title":"Dessert",
    "naic_code":72251,
    "sic_code":"5812"
  },
  {
    "category_id":344,
    "parent_category_id":338,
    "category_level":3,
    "title":"Ice Cream Parlors",
    "naic_code":72251,
    "sic_code":"2024"
  },
  {
    "category_id":345,
    "parent_category_id":338,
    "category_level":3,
    "title":"Internet Cafes",
    "naic_code":72251,
    "sic_code":"5800"
  },
  {
    "category_id":349,
    "parent_category_id":347,
    "category_level":4,
    "title":"Barbecue",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":351,
    "parent_category_id":347,
    "category_level":4,
    "title":"Burgers",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":353,
    "parent_category_id":347,
    "category_level":4,
    "title":"Delis",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":355,
    "parent_category_id":347,
    "category_level":4,
    "title":"Fast Food",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":357,
    "parent_category_id":347,
    "category_level":4,
    "title":"Indian",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":360,
    "parent_category_id":347,
    "category_level":4,
    "title":"Korean",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":361,
    "parent_category_id":347,
    "category_level":4,
    "title":"Mexican",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":362,
    "parent_category_id":347,
    "category_level":4,
    "title":"Middle Eastern",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":364,
    "parent_category_id":347,
    "category_level":4,
    "title":"Seafood",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":365,
    "parent_category_id":347,
    "category_level":4,
    "title":"Steakhouses",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":367,
    "parent_category_id":347,
    "category_level":4,
    "title":"Thai",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":368,
    "parent_category_id":347,
    "category_level":4,
    "title":"Vegan and Vegetarian",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":384,
    "parent_category_id":372,
    "category_level":2,
    "title":"Gymnastics",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":400,
    "parent_category_id":372,
    "category_level":2,
    "title":"Recreation Centers",
    "naic_code":713940,
    "sic_code":"7997"
  },
  {
    "category_id":402,
    "parent_category_id":372,
    "category_level":2,
    "title":"Skating",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":403,
    "parent_category_id":372,
    "category_level":2,
    "title":"Snow Sports",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":358,
    "parent_category_id":347,
    "category_level":4,
    "title":"Italian",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":359,
    "parent_category_id":347,
    "category_level":4,
    "title":"Japanese",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":323,
    "parent_category_id":317,
    "category_level":3,
    "title":"Carnivals",
    "naic_code":7131,
    "sic_code":"7999"
  },
  {
    "category_id":324,
    "parent_category_id":317,
    "category_level":3,
    "title":"Casinos and Gaming",
    "naic_code":713210,
    "sic_code":"7999"
  },
  {
    "category_id":326,
    "parent_category_id":317,
    "category_level":3,
    "title":"Dance Halls and Saloons",
    "naic_code":7224,
    "sic_code":"7910"
  },
  {
    "category_id":340,
    "parent_category_id":338,
    "category_level":3,
    "title":"Bakeries",
    "naic_code":311811,
    "sic_code":"5460"
  },
  {
    "category_id":341,
    "parent_category_id":338,
    "category_level":3,
    "title":"Breweries",
    "naic_code":312120,
    "sic_code":"2082"
  },
  {
    "category_id":342,
    "parent_category_id":338,
    "category_level":3,
    "title":"Cafes, Coffee and Tea Houses",
    "naic_code":72251,
    "sic_code":"5800"
  },
  {
    "category_id":346,
    "parent_category_id":338,
    "category_level":3,
    "title":"Juice Bars and Smoothies",
    "naic_code":72251,
    "sic_code":"5813"
  },
  {
    "category_id":352,
    "parent_category_id":347,
    "category_level":4,
    "title":"Chinese",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":369,
    "parent_category_id":308,
    "category_level":2,
    "title":"Country Clubs",
    "naic_code":7224,
    "sic_code":"5813"
  },
  {
    "category_id":370,
    "parent_category_id":308,
    "category_level":2,
    "title":"Wineries and Vineyards",
    "naic_code":31213,
    "sic_code":"2084"
  },
  {
    "category_id":371,
    "parent_category_id":308,
    "category_level":2,
    "title":"Zoos, Aquariums and Wildlife Sanctuaries",
    "naic_code":71213,
    "sic_code":"8420"
  },
  {
    "category_id":373,
    "parent_category_id":372,
    "category_level":2,
    "title":"Athletic Fields",
    "naic_code":7139,
    "sic_code":null
  },
  {
    "category_id":374,
    "parent_category_id":372,
    "category_level":2,
    "title":"Baseball",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":375,
    "parent_category_id":374,
    "category_level":3,
    "title":"Batting Ranges",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":376,
    "parent_category_id":372,
    "category_level":2,
    "title":"Basketball",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":377,
    "parent_category_id":372,
    "category_level":2,
    "title":"Combat Sports",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":379,
    "parent_category_id":372,
    "category_level":2,
    "title":"Dance",
    "naic_code":711120,
    "sic_code":"7997"
  },
  {
    "category_id":380,
    "parent_category_id":372,
    "category_level":2,
    "title":"Equestrian",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":366,
    "parent_category_id":347,
    "category_level":4,
    "title":"Sushi",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":325,
    "parent_category_id":317,
    "category_level":3,
    "title":"Circuses",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":381,
    "parent_category_id":372,
    "category_level":2,
    "title":"Football",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":383,
    "parent_category_id":372,
    "category_level":2,
    "title":"Gun Ranges",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":385,
    "parent_category_id":372,
    "category_level":2,
    "title":"Gyms and Fitness Centers",
    "naic_code":713940,
    "sic_code":"7997"
  },
  {
    "category_id":386,
    "parent_category_id":372,
    "category_level":2,
    "title":"Hockey",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":388,
    "parent_category_id":387,
    "category_level":3,
    "title":"Campgrounds and RV Parks",
    "naic_code":721211,
    "sic_code":"7030"
  },
  {
    "category_id":389,
    "parent_category_id":387,
    "category_level":3,
    "title":"Hiking",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":390,
    "parent_category_id":387,
    "category_level":3,
    "title":"Hot Air Balloons",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":391,
    "parent_category_id":387,
    "category_level":3,
    "title":"Hunting and Fishing",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":392,
    "parent_category_id":387,
    "category_level":3,
    "title":"Rock Climbing",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":393,
    "parent_category_id":387,
    "category_level":3,
    "title":"Skydiving",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":394,
    "parent_category_id":372,
    "category_level":2,
    "title":"Paintball",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":395,
    "parent_category_id":372,
    "category_level":2,
    "title":"Personal Trainers",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":396,
    "parent_category_id":372,
    "category_level":2,
    "title":"Race Tracks",
    "naic_code":711212,
    "sic_code":"7948"
  },
  {
    "category_id":398,
    "parent_category_id":397,
    "category_level":3,
    "title":"Racquetball",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":399,
    "parent_category_id":397,
    "category_level":3,
    "title":"Tennis",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":401,
    "parent_category_id":372,
    "category_level":2,
    "title":"Running",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":465,
    "parent_category_id":217,
    "category_level":3,
    "title":"Convention Centers",
    "naic_code":531120,
    "sic_code":"6512"
  },
  {
    "category_id":466,
    "parent_category_id":62,
    "category_level":2,
    "title":"Optometrist",
    "naic_code":621320,
    "sic_code":"8042"
  },
  {
    "category_id":382,
    "parent_category_id":372,
    "category_level":2,
    "title":"Golf",
    "naic_code":713910,
    "sic_code":"7992"
  },
  {
    "category_id":397,
    "parent_category_id":372,
    "category_level":2,
    "title":"Racquet Sports",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":405,
    "parent_category_id":372,
    "category_level":2,
    "title":"Sports Clubs",
    "naic_code":711211,
    "sic_code":"7941"
  },
  {
    "category_id":406,
    "parent_category_id":372,
    "category_level":2,
    "title":"Stadiums and Arenas",
    "naic_code":71121,
    "sic_code":"7940"
  },
  {
    "category_id":407,
    "parent_category_id":372,
    "category_level":2,
    "title":"Swimming Pools",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":409,
    "parent_category_id":408,
    "category_level":3,
    "title":"Boating",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":410,
    "parent_category_id":408,
    "category_level":3,
    "title":"Canoes and Kayaks",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":411,
    "parent_category_id":408,
    "category_level":3,
    "title":"Rafting",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":412,
    "parent_category_id":408,
    "category_level":3,
    "title":"Scuba Diving",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":414,
    "parent_category_id":372,
    "category_level":2,
    "title":"Yoga and Pilates",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":416,
    "parent_category_id":415,
    "category_level":2,
    "title":"Airlines and Aviation Services",
    "naic_code":481111,
    "sic_code":"4580"
  },
  {
    "category_id":417,
    "parent_category_id":415,
    "category_level":2,
    "title":"Gas Stations",
    "naic_code":447,
    "sic_code":"5540"
  },
  {
    "category_id":418,
    "parent_category_id":415,
    "category_level":2,
    "title":"Parking",
    "naic_code":812930,
    "sic_code":"7520"
  },
  {
    "category_id":419,
    "parent_category_id":415,
    "category_level":2,
    "title":"Public Transportation Services",
    "naic_code":485,
    "sic_code":"4100"
  },
  {
    "category_id":420,
    "parent_category_id":415,
    "category_level":2,
    "title":"Taxi and Car Services",
    "naic_code":4853,
    "sic_code":"4120"
  },
  {
    "category_id":421,
    "parent_category_id":420,
    "category_level":3,
    "title":"Car and Truck Rentals",
    "naic_code":532111,
    "sic_code":"7512"
  },
  {
    "category_id":422,
    "parent_category_id":420,
    "category_level":3,
    "title":"Charter Buses",
    "naic_code":48551,
    "sic_code":"4140"
  },
  {
    "category_id":423,
    "parent_category_id":420,
    "category_level":3,
    "title":"Limos and Chauffeurs",
    "naic_code":485320,
    "sic_code":"4119"
  },
  {
    "category_id":424,
    "parent_category_id":415,
    "category_level":2,
    "title":"Transport Hubs",
    "naic_code":488,
    "sic_code":"4780"
  },
  {
    "category_id":425,
    "parent_category_id":424,
    "category_level":3,
    "title":"Airports",
    "naic_code":48811,
    "sic_code":"4580"
  },
  {
    "category_id":426,
    "parent_category_id":424,
    "category_level":3,
    "title":"Bus Stations",
    "naic_code":485210,
    "sic_code":"4171"
  },
  {
    "category_id":427,
    "parent_category_id":424,
    "category_level":3,
    "title":"Heliports",
    "naic_code":488119,
    "sic_code":"4580"
  },
  {
    "category_id":413,
    "parent_category_id":408,
    "category_level":3,
    "title":"Swimming",
    "naic_code":7139,
    "sic_code":"7997"
  },
  {
    "category_id":428,
    "parent_category_id":424,
    "category_level":3,
    "title":"Ports",
    "naic_code":488310,
    "sic_code":"4780"
  },
  {
    "category_id":429,
    "parent_category_id":424,
    "category_level":3,
    "title":"Rail Stations",
    "naic_code":48211,
    "sic_code":"4780"
  },
  {
    "category_id":450,
    "parent_category_id":177,
    "category_level":2,
    "title":"Translation Services",
    "naic_code":541930,
    "sic_code":"7389"
  },
  {
    "category_id":447,
    "parent_category_id":177,
    "category_level":2,
    "title":"Construction",
    "naic_code":23,
    "sic_code":"1629"
  },
  {
    "category_id":431,
    "parent_category_id":430,
    "category_level":2,
    "title":"Cruises",
    "naic_code":483112,
    "sic_code":"4460"
  },
  {
    "category_id":432,
    "parent_category_id":430,
    "category_level":2,
    "title":"Lodging",
    "naic_code":7211,
    "sic_code":"7000"
  },
  {
    "category_id":433,
    "parent_category_id":432,
    "category_level":3,
    "title":"Bed and Breakfasts",
    "naic_code":721191,
    "sic_code":"7020"
  },
  {
    "category_id":434,
    "parent_category_id":432,
    "category_level":3,
    "title":"Cottages and Cabins",
    "naic_code":72119,
    "sic_code":"7000"
  },
  {
    "category_id":436,
    "parent_category_id":432,
    "category_level":3,
    "title":"Hotels and Motels",
    "naic_code":72111,
    "sic_code":"7010"
  },
  {
    "category_id":445,
    "parent_category_id":123,
    "category_level":2,
    "title":"Party Supplies",
    "naic_code":45299,
    "sic_code":"5531"
  },
  {
    "category_id":449,
    "parent_category_id":177,
    "category_level":2,
    "title":"Photography",
    "naic_code":54192,
    "sic_code":"7335"
  },
  {
    "category_id":451,
    "parent_category_id":382,
    "category_level":3,
    "title":"Golf Courses",
    "naic_code":713910,
    "sic_code":"7992"
  },
  {
    "category_id":452,
    "parent_category_id":408,
    "category_level":3,
    "title":"Surfing",
    "naic_code":7139,
    "sic_code":"7999"
  },
  {
    "category_id":454,
    "parent_category_id":460,
    "category_level":3,
    "title":"Infrastructure",
    "naic_code":517110,
    "sic_code":"4813"
  },
  {
    "category_id":455,
    "parent_category_id":460,
    "category_level":3,
    "title":"Mobile",
    "naic_code":443142,
    "sic_code":"5065"
  },
  {
    "category_id":456,
    "parent_category_id":460,
    "category_level":3,
    "title":"Advertising",
    "naic_code":541810,
    "sic_code":"7311"
  },
  {
    "category_id":460,
    "parent_category_id":177,
    "category_level":2,
    "title":"Technology",
    "naic_code":4431,
    "sic_code":"5731"
  },
  {
    "category_id":461,
    "parent_category_id":118,
    "category_level":3,
    "title":"Dog Parks",
    "naic_code":924120,
    "sic_code":"9512"
  },
  {
    "category_id":464,
    "parent_category_id":347,
    "category_level":4,
    "title":"International",
    "naic_code":7225,
    "sic_code":"5812"
  },
  {
    "category_id":463,
    "parent_category_id":317,
    "category_level":3,
    "title":"Arcades",
    "naic_code":713120,
    "sic_code":"7993"
  },
  {
    "category_id":457,
    "parent_category_id":347,
    "category_level":4,
    "title":"Asian",
    "naic_code":7225,
    "sic_code":"5812"}
];
